models:
  - name: googlenet-v3-tf
    launchers:
      - framework: tf
        model: inception_v3_2016_08_28_frozen.pb
        inputs:
          - name: input
        adapter: classification
    datasets:
      - name: imagenet_1001_classes
        preprocessing:
          - type: bgr_to_rgb
          - type: crop
            central_fraction: 0.875
          - type: resize
            size: 299
          - type: normalization
            mean: 127.5
            std: 127.5

  - name: googlenet-v3
    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: imagenet_1001_classes
        preprocessing:
          - type: crop
            central_fraction: 0.875
          - type: resize
            size: 299

  - name: inceptionv3
    launchers:
      - framework: tvm
        adapter: classification
        device: OpenCL
        model: mace_inceptionv3.fp16.fp16
        inputs:
          - name: input
            layout: NHWC
            shape: 1,299,299,3

      - framework: snpe
        adapter: classification
        model: models/snpe/mace_inception-v3.dlc
        inputs:
          - name: input
            layout: NHWC
            shape: 1,299,299,3

      - framework: tflite
        adapter: classification
        model: models/tflite/mace_inception-v3.tflite
        inputs:
          - name: input
            layout: NHWC
            shape: 1,299,299,3


      - framework: tvm
        adapter: classification
        device: CPU
        model: inceptionv3-tvm-CPU
        inputs:
          - name: input
            layout: NHWC
            shape: 1,299,299,3

    datasets:
      - name: imagenet_1001_classes
        preprocessing:
          - type: crop
            central_fraction: 0.875
          - type: resize
            size: 299
          - type: bgr_to_rgb
          - type: normalization
            mean: 127.5
            std: 127.5
